format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$nix_shell\
$python\
$sudo\
$cmd_duration\
$nodejs\
$line_break\
$jobs\
$time\
$status\
$shell\
$character"""

command_timeout = 1000

[nodejs]
format = "[$version](bold green)"

[directory]
truncate_to_repo = false
truncation_length = 5

[hostname]
style = "green"
